### ISSUE TITLE
Add footer text from config file

### ISSUE THREAD

**Issue by jpkeyw** [jeffshaver/safe-app#128]
See Jira ticket 216.

**Comment by jeffshaver** [comment]
This could probably be accomplished by separating top and bottom banner text config options.

**Comment by jpkeyw** [comment]
Actually, the top and bottom banners are different than this. See the Jira ticket for the details. These will also be in the config file, but be in blocks above the bottom banner text, probably one floating left and one floating right along the bottom. Yay CSS.
