### ISSUE TITLE
Leftnav help menu broken

### ISSUE THREAD

**Issue by jpkeyw** [jeffshaver/safe-app#183]
With the change to icons only in the left nav, the help menu is broken.
![image](https://cloud.githubusercontent.com/assets/17475109/16687983/c818f626-44e9-11e6-9f70-1b9125a61b0c.png)

**Comment by jpkeyw** [comment]
Instead of a `ListItem` with `nestedItems`, should probably be an [Icon Menu](http://www.material-ui.com/#/components/icon-menu).

**Comment by jeffshaver** [comment]
maybe put the help icon in the left nav if helpMenuItems exists, but on-click have a pop-over to the right come up that has the items in it? instead of it expanding?

**Comment by jpkeyw** [comment]
Take a look at Icon Menu. That's essentially what it is: pops out a menu to the right and downwards (by default) instead of expanding downwards. I already have it working. Just working on getting the stupid help icon to show up correctly positioned. Ugh.
