### ISSUE TITLE
investigate phantomjs for headless testing

### ISSUE THREAD

**Issue by cafedavid** [jeffshaver/safe-app#25]

**Comment by jeffshaver** [comment]
I was actually thinking about using jest: http://facebook.github.io/jest/docs/tutorial-react.html#content

This could be a way to keep our unit tests and ui tests in sync. This way we could use jest for everything instead of jest for ui and mocha for unit.

**Comment by cafedavid** [comment]
yea, i have no preferences - testers raised phantomjs as a possibility. we need to collaborate with testers to determine their needs/goals and give them a few options to begin researching

**Comment by knorris** [comment]
I found this site interesting http://www.toptal.com/react/how-react-components-make-ui-testing-easy

**Comment by jeffshaver** [comment]
This is going to be closed. we will be using mocha, expect and react test utils to test (similar to the article that @knorris posted)
