### ISSUE TITLE
change the h1 on the data/upload screen to a h2

### ISSUE THREAD

**Issue by jeffshaver** [jeffshaver/safe-app#51]
the h1 tag that has `Upload a Dataset` in it, should be changed to an h2 tag to match the other pages.

**Comment by jpkeyw** [comment]
It looks like this is OBE since I have h1 still and it matches the other pages?

**Comment by jeffshaver** [comment]
this is what i am seeing...

Data/Upload page:
![h1](https://cloud.githubusercontent.com/assets/5390616/14438635/140ebe60-fff5-11e5-8db9-5d25ea7a420f.png)

Settings page:
![h2](https://cloud.githubusercontent.com/assets/5390616/14438636/1444d70c-fff5-11e5-8f5a-688e71a1bd99.png)
