### ISSUE TITLE
should we clear shared state between views

### ISSUE THREAD

**Issue by jeffshaver** [jeffshaver/safe-app#60]
some screens share pieces of the global state. For example, the search and analytics screen both use the source and filters state from redux.

the question is: should that state be cleared between the two views or no? in some cases it seems beneficial and in some cases it doesn't.

**Comment by knorris** [comment]
Found this: connect() style implementation of storage a local state for reusable components
https://github.com/babotech/redux-state

**Comment by jeffshaver** [comment]
It seems like that is a way to store local state without using `this.setState`. I guess we could use this to save off state inside of `componentWillUnmount`. However, we would need to figure out how to restore that state to the global store inside of `componentWillMount`

**Comment by jeffshaver** [comment]
Here is a 10 line function that can allow us to rehydrate our stores: https://github.com/reactjs/redux/pull/658#issuecomment-136485851

all we would need other than that is to save the state off in localstorage in `componentWillUnmount`

**Comment by jeffshaver** [comment]
The decision has been to use state hydration/dehydration to save a pages shared state and restore it later. work ticket: #70
